// <auto-generated />
using System;
using DenunciasAmbientaisAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DenunciasAmbientaisAPI.Migrations
{
    [DbContext(typeof(SistemaDenunciasDBContext))]
    partial class SistemaDenunciasDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DenunciasAmbientaisAPI.Models.DenunciasModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataDenuncia")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataVerificacao")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("DenunciaEncaminhadaParaAutoridades")
                        .HasColumnType("bit");

                    b.Property<bool?>("DenunciaVerificada")
                        .HasColumnType("bit");

                    b.Property<string>("DescricaoDenuncia")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("FotoDenuncia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LocalDenuncia")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("QualAutoridadeFoiEncaminhada")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Denuncias");
                });
#pragma warning restore 612, 618
        }
    }
}
